version: 0.0
os: linux
files:
  - source: /
    destination: /var/www
hooks:
  BeforeInstall:
    - location: /var/www/create-web-dir.sh
      timeout: 300
      runas: ubuntu #run as root 
  ApplicationStart:
    - location: /var/www/start.sh
      timeout: 300
      runas: ubuntu #run as root 
